spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uchat
    username: root
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    caffeine:
      spec: maximumSize=100
